---
title: "Math 557 Sep 15"
---

# Completing Theories

## Key Concepts

- We previously defined the *term model* $\mathcal{A}$. It holds that for any *atomic* sentence $\sigma$, 
$$\mathcal{A} \models \sigma \quad \iff \quad T \vdash \sigma$$

- Trying to extend this to arbitrary sentence via induction, the *negation case* looks like
$$\mathcal{A} \models \neg\sigma \; \iff \;  \mathcal{A} \nvDash \sigma \; \overset{\text{ind hyp}}{\iff} \; T \nvdash \sigma$$
We would like to show that this is equivalent to $T \vdash \neg\sigma$.  

- One direction follows from $T$ being consistent, but for the other direction, $T$ may not be strong enough to prove this. 

- We therefore need to *extend* $T$ to a complete theory.



## Problems


:::{#exr-}
\
Verify that indeed for all atomic sentences $\sigma$,
$$\mathcal{A} \models \sigma \quad \iff \quad T \vdash \sigma$$
:::

::: {#exr-}
\
Recall that a theory $T$ is *maximally consistent* if it is consistent but does not have any consistent proper extensions. $T$ is called *deductively closed* if the deductive closure of $T$,
$$T^{\vdash} = \{ \sigma : T \vdash \sigma \}$$
is equal to $T$.

- Show that a maximally consistent theory is complete and deductively closed.
- Show that if $T$ is complete, then $T^{\vdash}$
is maximally consistent.
:::

::: {#exr-}
\
Is every consistent, deductively closed theory complete?
:::


::: {#exr-}
\
Show that the union of an increasing sequence of consistent theories is consistent. 
:::

::: {#exr-}
\
Extend Lindebaum's theorem on the existence of maximally consistent extension from countable to arbitrary languages.
:::


::: {#exr-}
\
Fix a language $\mathcal{L}$. Let $X$ be the set of all maximally consistent $\mathcal{L}$-theories. For an $\mathcal{L}$-sentence $\sigma$, let 
$$\langle \sigma \rangle = \{ T \in X \colon \sigma \in T\}$$

Show that

- $\langle \sigma \land \tau \rangle = \langle \sigma \rangle \cap \langle \tau \rangle$
- $\langle \neg\sigma \rangle = X \setminus \langle \sigma \rangle$
:::

::: {#exr-}
\
Continuing the previous exercise, let $\mathcal{O}$ be the topology generated by the sets $\langle \sigma \rangle$. Show that

- each $\langle \sigma \rangle$ is clopen,
- the $\langle \sigma \rangle$ form a basis for $\mathcal{O}$,
- $\mathcal{O}$ is Hausdorff.
:::


