---
title: "Math 557 Sep 19"
---

# Henkin Theories

## Key Concepts

- An $\mathcal{L}$-theory $T$ is a **Henkin theory** if for every sentence of the form $\exists x \psi$ there exists a constant $\mathcal{L}$-term $t$ such that 
$$
    T \vdash_{\mathcal{L}} \exists x \psi \; \to \; \psi_{t/x}
$$

- **Questions:**

    - What are Henkin theories needed for?
    - Do they exist? 
    - Can we extend a given consistent theory to a Henkin theory that is still consistent?



## Problems


:::{#exr-}
\
As before, let $\mathcal{A}_T$ be the term model of $T$. Pinpoint exactly where we might run into difficulties when we are trying to prove
$$
\mathcal{A}_T \models \exists x \psi \; \iff \; T \vdash_{\mathcal{L}} \exists x \psi
$$
:::

::: {#exr-}
## Interlude
\
What if in $\exists x \psi$ the variable $x$ is not free? Does that make a difference regarding being a Henkin theory?
:::


::: {#exr-}
\
Can you find examples of a Henkin theories (without needing to extend the lenaguage)?
:::


The basic construction step for extending an $\mathcal{L}$-theory $T$ to a Henkin theory is for every sentence of the form $\sigma \equiv \exists x \psi$,

- add a new constant symbol $c_\sigma$ to $\mathcal{L}$
- add the formula $\exists x \psi \; \to \; \psi_{c_\sigma/x}$ to $T$.


::: {#exr-}
\
Why could the addition of a constant theoretically lead to $T$ being inconsistent, even though $T$ itself remains unchanged?

And why does $T$ actually remain consistent?
:::


The Henkin extension $T_H$ of $T$ is obtained by an iterative process:

Single iteration step:

- $\mathcal{L}' = \mathcal{L} \cup \{c_\sigma \colon \sigma \: \mathcal{L}\text{-sentence of the form } \exists x \psi \}$
- $\Gamma = \{ \exists x \psi(x) \to \psi_{c_\sigma/x} \colon \sigma \: \mathcal{L}\text{-sentence of the form } \exists x \psi \}$ 
- $T' = T \cup \Gamma$ (an $\mathcal{L}'$-theory)

::: {#exr-}
\
Why is $T'$ above not necessarily a Henkin theory?
:::


Iteration process:

- $\mathcal{L}_0 = \mathcal{L}, \; T_0 = T$
- $\mathcal{L}_{n+1} = \mathcal{L}'_n, \; T_{n+1} = T_n'$
- $\textstyle \mathcal{L}_H = \bigcup_{n \in \mathbb{N}} \mathcal{L}_n, \; T_H = \bigcup_{n \in \mathbb{N}} T_n$

::: {#exr-}
\
Why is $T_H$ a Henkin theory?
:::

$T_H$ is no longer a purely symbolic extension of $T$ (in the sense that we simply extend the language), since we add new sentences to $T$ (the sentences in $\Gamma$ for each iteration step).

::: {.callout-important}
## Take-home Problem
\
Show that for every $\mathcal{L}$-formula $\varphi$,
$$
T_H \vdash_{\mathcal{L}_H} \varphi \; \iff \; T \vdash_{\mathcal{L}} \varphi
$$

(*You can find some hints in the video lecture.*)
:::