---
title: "Math 557 Sep 26"
---

# Midterm 1 Review


:::{.callout-important}
## Take-home Problem 1
\
Prove unique readability for the set of $\mathcal{L}$-formulas.
:::

::: {#sol-1}
\
**First** prove **readibility**, i.e. the statement that for any $\mathcal{L}$-formula $\varphi$, exactly one of the following cases holds:

(1) There exist terms $s,t$ such that $\varphi \equiv s=t$.
(2) There exists a relation symbol $R$ and, if $n$ is the arity of $R$, terms $t_1, \dots, t_n$ sucht that $\varphi \equiv Rt_1\dots t_n$.
(3) There exists a formula $\psi$ such that $\varphi \equiv \neg \psi$.
(4) There exist formulas $\psi, \theta$ such that $\varphi \equiv (\psi \land \theta)$.
(5) There exists a variable $x$ and a formula $\psi$ such that $\varphi \equiv \exists x \psi$.

To see this, let $F$ be the subset of $\mathcal{L}^*$ such that every $\theta \in F$ satisfies exactly one of (1)-(5). Then $F$ contains all atomic formulas and is closed under $\neg, \land, \exists x$. Since the set of $\mathcal{L}$-formulas is the smallest such set, it follows that every $\mathcal{L}$-formula is contained in $F$, and therefore has the desired property.


**Second** we argue that a proper initial segment of a formula cannot be a formula. We proceed by induction on the length $l$ of $\varphi$. For $l=1$ there is no formula of that length. Now suppose $\varphi$ is a formula of length $l+1$, and $\beta$ is a proper initial segment. We may assume $\beta$ is not empty. We consider theses (1)-(5) from readability.

Case $\varphi \equiv s=t$
: Either $\beta \equiv s = t'$ with $t \subset t'$, but this would contradict that no proper initial segment of a term is a term. Or $\beta \equiv s=$: An easy induction over the length of a formula shows that no formula ends with $=$. Or $\beta \subseteq s$. Another easy induction shows that no formula can be a term or an initial segment of a term.

Case $\varphi \equiv Rt_1\dots t_n$
: If $\beta$ were a formula, it has to be of the form $Rs_1\dots s_n$. Comparing terms, we would see that one of the $s_i$ is a proper initial segment of some $t_j$, which is impossible.

Case $\varphi \equiv \neg \theta$
: Then $\beta \equiv \neg \beta'$ with $\beta'$ a proper initial segment of $\theta$. By inductive hypothesis, $\beta'$ is not a formula, hence $\neg \beta'$ is not a formula either.

Case $\varphi \equiv (\psi \land \theta)$
: Then $\beta$ starts with $($ but does not end with $)$. Another induction shows that for any formula, the number of $($'s always equals the number of $)$'s.

Case $\varphi \equiv \exists x \varphi$
: Neither '$\exists$' nor '$\exists x$' are formulas. If $\beta$ is longer than that, it is of the form $\exists x \beta'$. By inductive hypothesis, $\beta'$ is not a formula, and hence $\beta$ is not a formula (by readability).


**Finally**, we prove **unique readability**: The choices in (1)-(5) are unique.

Case (1)
: Suppose $\varphi \equiv s=t \equiv s'=t'$. Since no proper initial segment of a term is a term, it must hold that $s\equiv s'$ and $t \equiv t'$.

Case (2)
: Suppose $\varphi \equiv Rt_1\dots t_n \equiv S s_1\dots s_k$. Then $R \equiv S$ and $n=k$. Comparing terms inductively, using again the fact that no proper initial segment of a term is a term, we get $s_i \equiv t_i$ for all $i$.

Case (3)
: Suppose $\varphi \equiv \neg \psi \equiv \neg \theta$. Immediately, we infer $\psi \equiv \theta$.

Case (4)
: Suppose $\varphi \equiv (\psi_1 \land \theta_1) \equiv (\psi_2\land \theta_2)$. Assume $\psi_1 \not\equiv \psi_2$. Then $\psi_1$ is a proper initial segment of $\psi_2$ or vice versa (since both of them are part of $\varphi$). Either case is impossible due to the fact that no proper initial segment of a formula is a formula. Hence $\psi_1 \equiv \psi_2$ and thus also $\theta_1 \equiv \theta_2$.

Case (5)
: Suppose $\varphi \equiv \exists x \psi \equiv \exists y \theta$. By comparing entries, we get $x \equiv y$ and thus \psi \equiv \theta$, as desired.
:::
 


:::{.callout-important}
## Take-home Problem 2
\
Let $\mathcal{L}$ be any finite language and let $\mathcal{M}$ be a finite $\mathcal{L}$-structure. Show
that there is an $\mathcal{L}$-sentence $\varphi$ such that 
$$
\mathcal{N} \models \varphi \; \iff \; \mathcal{N} \cong \mathcal{M}.
$$
:::

::: {#sol-2}
\
Suppose $\mathcal{L} = \{c_1, \cdots, c_k, f_1^{(a_1)}, \dots f_l^{(a_l)}, R_1^{(b_1)}, \dots, R_j^{(b_j)} \}$ where the $(a_i), (b_m)$ denote the arities of the respective symbols.

Since $\mathcal{M}$ is finite, we may assume $M = \{1, \dots, n\}$ for some $n \in \mathbb{N}$.

The basic idea is to collect all "elementary facts" about $\mathcal{M}$ in a single formula (think of a *group multiplication table*, just for all functions and relations).

Define
\begin{align}
\varphi \equiv \; \exists x_1, \dots, x_n   \biggl ( & \bigwedge_{i \neq m} x_i \neq x_l \; \land \; \forall y \bigvee_{i \leq n} y = x_i \\
& \land \bigwedge_{i \leq k} c_i = x_{c^{\mathcal{M}}_i} \\
& \land \bigwedge_{i\leq l} \bigwedge_{\pi \in \{1,\dots, n\}^{a_i}} f_i x_{\pi(1)} \dots x_{\pi(a_i)} = x_{f^\mathcal{M}_i(\pi(1), \dots, \pi(a_i))} \\
& \land \bigwedge_{i\leq j} \bigwedge_{\pi \in \{1,\dots, n\}^{b_i}} \delta_\pi R_i x_{\pi(1)} \dots x_{\pi(b_i)} \biggr )
\end{align}
where $\delta_\pi$ is empty if $R(\pi(1), \dots, \pi(b_i))$ holds in $\mathcal{M}$, and $\neg$ if not.

Assme $\mathcal{N} \models \varphi$. Due to the first line of the equation, $N$ has exactly $n$ elements, and let $r_i \in N$ be the witness to $\exists x_i$. Define a mapping $\tau: M \to N$ by letting $\tau(i) = r_i$. We claim that $\tau$ is an isomorphism.

By definition we have $\tau(c_i^\mathcal{M}) = r_{c_i^\mathcal{M}}$. Moreover, by the second line of the formula, $r_{c^\mathcal{M}_i}$ is the unique element of $N$ that makes the formula $c_i = x_{c_i^\mathcal{M}}$ true. It follows that $\tau(c_i^\mathcal{M}) = c_i^\mathcal{N}$ for all $1 \leq i \leq k$.

Using a similar argument with the third line of the formula, we obtain
$$
\tau(f_i^\mathcal{M}(s_1, \dots, s_{a_i})) = r_{f_i^\mathcal{M}(s_1, \dots, s_{a_i})} = f^\mathcal{N}(r_{s_1}, \dots, r_{s_{a_i}}) = f^\mathcal{N}(\tau(s_1), \dots, \tau(s_{a_i})
$$
The argument for $R^\mathcal{M}(s_1, \dots, s_{b_i}) \iff R^\mathcal{N}(\tau(s_1), \dots, \tau(s_{b_i}))$ is similar.

On the other hand, if $\mathcal{M} \cong \mathcal{N}$ via $\tau$, then $\mathcal{N} \models \psi[\tau(1), \dots, \tau(n)]$, where $\psi$ is such that $\varphi \equiv \exists x_1, \dots, x_n \: \psi$,  due to the fact that $\tau$ is an isomorphism, and thus $\mathcal{N} \models \varphi$.
:::


:::{.callout-important}
## Take-home Problem
\
Give an example of a language $\mathcal{L}$ and an $\mathcal{L}$-sentence $\psi$ such that

- there is at least one $\mathcal{L}$-structure $\cal A$ such that $\cal A \models \psi$,
- for all $\cal L$-structures $\cal A$, if $\cal A \models \psi$, then the universe $A$ of $\cal A$ is infinite.
:::


:::{.callout-important}
## Take-home problem
\
Show that 

\begin{align*}
\{\varphi \to \psi \} & \vdash \exists x \varphi \: \to \: \exists x \psi \\
\{\varphi \to \psi \} & \vdash \forall x \varphi \: \to \: \forall x \psi \\
\end{align*}
:::


::: {.callout-important}
## Take-home Problem
\
Show that for every $\mathcal{L}$-formula $\varphi$,
$$
T_H \vdash_{\mathcal{L}_H} \varphi \; \iff \; T \vdash_{\mathcal{L}} \varphi
$$
:::


::: {.callout-important}
## Take-home Problem
\
Use the compactness theorem to show (without using the Axiom of Choice) that every set can be linearly ordered.

Try to strengthen this to:

> Every partial order can be extended to a linear order.
:::
