---
title: "Math 557 Nov 5"
---

Of particular importance is that $\Delta_0$-formulas mean the same thing in a structure as in all end extensions:

# Preservation Properties under End Extensions {#preservation}

::: Theorem
Let $\mathcal{N}, \mathcal{M}$ be structures of the language $L$ of $\mathsf{PA}^-$, with $\mathcal{N} \subseteq_{end} \mathcal{M}$, and let $\vec{a} \in N$. Then:

1. Every $\Delta_0$-formula $\varphi(\vec{v})$ is **absolute**:
$$
\mathcal{N}\models \varphi[\vec{a}] \iff \mathcal{M}\models \varphi[\vec{a}],
$$

2. Every $\Sigma_1$-formula $\varphi(\vec{v})$ is **upward-persistent**:
$$
\mathcal{N}\models \varphi[\vec{a}] \Longrightarrow \mathcal{M}\models \varphi[\vec{a}],
$$

3. Every $\Pi_1$-formula $\varphi(\vec{v})$ is **downward-persistent**:
$$
\mathcal{M}\models \varphi[\vec{a}] \Longrightarrow \mathcal{N}\models \varphi[\vec{a}],
$$

4. Every $\Delta_1$-formula $\varphi(\vec{v})$ is **absolute**:
$$
\mathcal{N}\models \varphi[\vec{a}] \iff \mathcal{M}\models \varphi[\vec{a}].
$$
:::

::: {.proof}
We prove (i) by induction on the formula construction of $\varphi(\vec{v})$, where only the case of a bounded quantifier is of interest. But since $\mathcal{M}$ is an end extension of $\mathcal{N}$, $M$ does not insert any new elements below an element of $N$, so that a bounded quantifier means the same thing in both structures.
:::

Let $\Sigma_1$-$Th(\mathbb{N}):= \{\sigma \mid \sigma \text{ is a } \Sigma_1\text{-sentence with } \mathbb{N} \models \sigma \}$. Then we have:

## Corollary

$$
\mathsf{PA}^- \models \Sigma_1\text{-}Th(\mathbb{N})
$$

::: {.proof}
Let $\mathcal{N} \models \mathsf{PA}^-$. By the previous theorem, we may assume that $\mathbb{N} \subseteq_{end} \mathcal{N}$, and the claim then follows from part (ii) above.
:::

Thus one can prove in the theory $\mathsf{PA}^-$ all $\Sigma_1$-sentences that hold in the standard model, but not all true $\Pi_1$-sentences anymore. For instance, the $\Pi_1$-sentence stating that every number is even or odd:
$$
(*) \quad \forall x \;  \exists y \le x \; (x = 2 \cdot y \vee x = 2 \cdot y +1)
$$
is true in the standard model, but not in the $\mathsf{PA}^-$-model $\mathbb{Z}[X]^+$.

Even true $\forall$-sentences (i.e., sentences of the form $\forall \vec{x} \; \psi$ with *quantifier-free* $\psi$) that hold in the standard model need not be provable in $\mathsf{PA}^-$. For example, the $\forall$-sentence
$$
\forall x,y  (x^2 \ne 2 \cdot y^2)
$$
is true in the standard model, but not provable in $\mathsf{PA}^-$ ($\mathbb{Z}/(X^2 - 2Y^2)$ is a counterexample).

Thus the above sentence (*) is an example of a $\Pi_1$-sentence that is not a $\forall$-sentence, where one cannot omit the bounded quantifier! (By the way, one can easily show that $\mathbb{Z}[X]^+$ is at least a model of all $\forall$-sentences that hold in the standard model.)
